### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by naziko2411** [BoredBrick/Instagram-account-tracker#1]
Hello! First of all, thank you for making the amazing project. I am a newbie coder, which program should I use from this script? Also, I will track every single account in Instagram since I am trying to search it since early 2020.

**Comment by BoredBrick** [comment]
Hello, I used Windows task planner to set the program to run once every day.
As for the second question, I am not entirely sure what you mean by it. This program is made to only track one account. It can track any account that you have access to from your profile.
